name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch: # Omogućava ručno pokretanje workflow-a

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout koda
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Simulacija build procesa
      - name: Generate build
        run: echo "This is a simulated build step" > build.log

      # 3. Upload fajlova na GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: . # Lokacija tvojih fajlova
