name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch: # Omogućava ručno pokretanje workflow-a iz Actions taba.

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout koda
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Testiranje HTML fajlova
      - name: Install HTMLHint for testing
        run: npm install -g htmlhint

      - name: Test HTML files
        run: htmlhint index.html # Testira glavni HTML fajl.

      # 3. Build korak (simulacija)
      - name: Build site (simulated)
        run: echo "Build completed at $(date)" > build.log

      # 4. Deploy na GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: . # Folder gde su HTML fajlovi + build.log
